name: Build

on: [push]

env:
  CI_COMMIT_REF_NAME: ${{ github.ref_name }}

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - uses: deckhouse/modules-actions/lint@fix/dmt-lint
        env:
          DMT_METRICS_URL: ${{ secrets.DMT_METRICS_URL }}
          DMT_METRICS_TOKEN: ${{ secrets.DMT_METRICS_TOKEN }}
          DMT_METRICS_ID: "test-metrics-2"
          DMT_REPOSITORY: "https://github.com/juev/modules-template-3"

  build:
    runs-on: ubuntu-latest
    name: Build and Push images
    steps:
      - uses: actions/checkout@v4

      - uses: deckhouse/modules-actions/setup@main
        with:
          registry: ghcr.io
          registry_login: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the repository name
        id: repo_name
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | cut -d'/' -f2)" >> $GITHUB_OUTPUT

      - uses: deckhouse/modules-actions/build@main
        with:
          module_source: ghcr.io/${{ github.repository_owner }}/modules
          module_name: ${{ steps.repo_name.outputs.REPO_NAME }}
          module_tag: ${{ github.ref_name }}
